Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Naming/FileName:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*_spec.rb'

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Max: 20

Bundler/OrderedGems:
  Enabled: false

Layout/LineLength:
  Max: 100

AllCops:
  Exclude:
    - 'app/views/**/*.slim'
