version: '3'

services:
  postgres:
    image: postgres:11-alpine
    expose:
      - 5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  web:
    image: orderingsystem:prod
    build:
      context: .
      dockerfile: Dockerfile.prod
    stdin_open: true
    tty: true
    ports:
      - 80:80
      - 443:443
    links:
      - postgres
