version: '3.7'
x-public-data:
  &public-data
  type: bind
  source: ./web/public
  target: /web/public
  volume:
    copy_on: up
x-tmp-data:
  &tmp-data
  type: bind
  source: ./web/tmp
  target: /web/tmp
  volume:
    copy_on: up
x-log-data:
  &log-data
  type: bind
  source: ./web/log
  target: /web/log
  volume:
    copy_on: up
x-db-data:
  &db-data
  type: bind
  source: ./web/db
  target: /web/db
  volume:
    copy_on: up

services:
  nginx:
    build: nginx
    ports:
      - ${LOCAL_PORT}:${NGINX_PORT}
    volumes:
      - *public-data
      - *tmp-data
  web:
    build: web
    stdin_open: true
    tty: true
    environment:
      - RAILS_ENV=${RAILS_ENV}
    volumes:
      - ./web:/web
      - bundle-data:/bundle
      - *public-data
      - *tmp-data
      - *log-data
      - *db-data
  bundle:
    image: busybox
    volumes:
      - bundle-data:/bundle
  unbound:
    build: unbound
    ports:
      - ${UNBOUND_DNS_PORT}:${DNS_PORT}
      - ${UNBOUND_DNS_PORT}:${DNS_PORT}/udp
volumes:
  bundle-data:
