version: '3'

services:
  nginx:
    build: nginx
    ports:
      - ${LOCAL_PORT}:${NGINX_PORT}
  web:
    build: web
    stdin_open: true
    tty: true
    environment:
      - RAILS_ENV=${RAILS_ENV}
    volumes:
      - ./web:/web
      - bundle-data:/bundle
  bundle:
    image: busybox
    volumes:
      - bundle-data:/bundle
  unbound:
    build: unbound
    ports:
      - ${UNBOUND_DNS_PORT}:${DNS_PORT}
      - ${UNBOUND_DNS_PORT}:${DNS_PORT}/udp
volumes:
  bundle-data:
