version: '3'

services:
  postgres:
    image: postgres:11-alpine
    ports:
      - 5432:5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  devserver:
    user: app
    image: orderingsystem:dev
    command: ["/bin/bash", "-lc", "yarn dev:server"]
    ports:
      - 3035:3035
    volumes:
      - .:/home/app/web

  web:
    user: root
    image: orderingsystem:dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    stdin_open: true
    tty: true
    ports:
      - ${LOCAL_PORT}:3000
    volumes:
      - .:/home/app/web
      - bundle_gems:/usr/local/rvm/gems/ruby-2.6.3
    links:
      - postgres
      - devserver

volumes:
  bundle_gems:
