version: '3'

services:
  postgres:
    image: postgres:11-alpine
    expose:
      - 5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_NAME}
    restart: always

  web:
    image: czcdev/orderingsystem:0.3.0
    stdin_open: true
    tty: true
    links:
      - postgres
    environment:
      DB_PASSWORD: ${DB_PASSWORD}
      DB_USERNAME: ${DB_USERNAME}
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
      RAILS_ENV: production
    restart: always

  https-portal:
    image: steveltn/https-portal:1.7.2
    ports:
      - '80:80'
      - '443:443'
    links:
      - web
    environment:
      DOMAINS: 'orderingsystem.tk -> http://web'
      STAGE: 'production'
    restart: always
