version: '3'

services:
  postgres:
    image: postgres:11-alpine
    expose:
      - 5432
    volumes:
      - postgres:/var/lib/postgresql/data
  web:
    image: orderingsystem
    build:
      context: .
      dockerfile: Dockerfile.dev
    stdin_open: true
    tty: true
    ports:
      - ${LOCAL_PORT}:80
    volumes:
      - .:/home/app/web
      - bundle_gems:/usr/local/rvm/gems/ruby-2.5.3
    links:
      - postgres

volumes:
  bundle_gems:
  postgres:
