version: '3'

services:
  postgres:
    image: postgres:11-alpine
    expose:
      - 5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    restart: always

  web:
    image: orderingsystem:prod
    build:
      context: .
      dockerfile: Dockerfile.prod
    stdin_open: true
    tty: true
    links:
      - postgres
    restart: always

  https-portal:
    image: steveltn/https-portal:1.7.2
    ports:
      - '80:80'
      - '443:443'
    links:
      - web
    environment:
      DOMAINS: 'orderingsystem.tk -> http://web'
      STAGE: 'production'
      FORCE_RENEW: 'true'
    restart: always
