# https://circleci.com/docs/2.0/deployment-integrations/#capistrano
# https://github.com/CircleCI-Public/circleci-demo-docker/blob/docker-compose/.circleci/config.yml

version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.5.1-node-browsers
    steps:
      - checkout

      - run:
          name: Bundle install
          command: |
            cd web
            bundle check || bundle install

      - run:
          name: Setup environments
          command: |
            cd web
            RAILS_ENV=test bundle exec rails db:create
            RAILS_ENV=test bundle exec rails db:migrate

      - run:
          name: Run tests
          command: |
            cd web
            RAILS_ENV=test bundle exec rspec

  deploy:
    docker:
      - image: circleci/ruby:2.5.1-node-browsers
    steps:
      - checkout

      - run:
          name: Bundle install
          command: |
            cd web
            bundle check || bundle install

      - run:
          name: Setup enrivonments and create secret_key_base
          command: |
            cd web
            cp .env.sample .env
            echo "production:\n  secret_key_base: `bundle exec rails secret`" > config/secrets.yml

      - run:
          name: Deploy to DigitalOcean's server from production branch
          command: |
            cd web
            bundle exec cap production secrets_yml:setup
            bundle exec cap production deploy

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: production
