version: 2
jobs:
  rspec:
    machine: true
    steps:
      - checkout

      - restore_cache:
          keys:
            - yarn-dep-{{ checksum "yarn.lock" }}
            - yarn-dep-

      - restore_cache:
          keys:
            - gem-dep-{{ checksum "Gemfile.lock" }}
            - gem-dep-

      - run:
          name: Setup test environment
          command: |
            cp .env.sample .env
            bundle install --path .bundle -j4
            RAILS_ENV=test bundle exec rails db:create db:migrate db:seed

      - run:
          name: Create asset's manifest with dependency installation
          command: |
            cp .env.sample .env
            yarn
            bundle exec rails webpacker:compile

      - save_cache:
          paths:
            - node_modules
          key: yarn-dep-{{ checksum "yarn.lock" }}

      - save_cache:
          paths:
            - .bundle
          key: gem-dep-{{ checksum "Gemfile.lock" }}

      - run:
          name: Run tests
          command: |
            cp .env.sample .env
            RAILS_ENV=test web bundle exec rails spec

  build:
    machine: true
    step:
      - checkout

      - run:
          name: Build production image
          command: docker build .

workflows:
  version: 2
  build_test_and_deploy:
    jobs:
      - rspec
      - build
