# https://circleci.com/docs/2.0/deployment-integrations/#capistrano
# https://github.com/CircleCI-Public/circleci-demo-docker/blob/docker-compose/.circleci/config.yml

version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout

      - restore_cache:
          keys:
            - yarn-dep-{{ checksum "yarn.lock" }}
            - yarn-dep-

      - run:
          name: Install docker-compose
          command: |
            curl -L https://github.com/docker/compose/releases/download/1.19.0/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose

      - run:
          name: Build images
          command: |
            cp .env.sample .env
            docker-compose build

      - run:
          name: Setup test environment
          command: |
            cp .env.sample .env
            docker-compose run --rm web bundle install -j4
            docker-compose run --rm -e RAILS_ENV=test web bundle exec rails db:create
            docker-compose run --rm -e RAILS_ENV=test web bundle exec rails db:migrate
            docker-compose run --rm -e RAILS_ENV=test web bundle exec rails db:seed

      - run:
        name: Create asset's manifest with dependency installation
        command: |
          cp .env.samlple .env
          docker-compose run --rm web yarn
          docker-compose run --rm web yarn build

      - save_cache:
          paths:
            - node_modules
          key: yarn-dep-{{ checksum "yarn.lock" }}

      - run:
          name: Run tests
          command: |
            cp .env.sample .env
            docker-compose run --rm -e RAILS_ENV=test web bundle exec rspec

# TODO: configure remote server (Docker)
#   deploy:
#     docker:
#       - image: circleci/ruby:2.5.1-node-browsers
#     steps:
#       - checkout
#
#       - run:
#           name: Bundle install
#           command: |
#             cd web
#             bundle check || bundle install
#
#       - run:
#           name: Deploy to DigitalOcean's server from production branch
#           command: |
#             cd web
#             bundle exec cap production deploy
#
# workflows:
#   version: 2
#   build-deploy:
#     jobs:
#       - build
#       - deploy:
#           requires:
#             - build
#           filters:
#             branches:
#               only: production
