# https://circleci.com/docs/2.0/deployment-integrations/#capistrano
# https://github.com/CircleCI-Public/circleci-demo-docker/blob/docker-compose/.circleci/config.yml

version: 2
jobs:
  build:
    docker:
      - image: ubuntu:16.04
    steps:
      - checkout

      - setup_remote_docker

      - run:
          name: Install necessary tools
          command: apt-get update && apt-get install -y curl

      - run:
          name: Install Docker client
          command: |
            set -x
            VER="18.06.1-ce"
            curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            tar xzvf /tmp/docker-$VER.tgz
            mv docker/* /usr/bin

      - run:
          name: Install Docker compose
          command: |
            DOCKER_COMPOSE_VERSION=1.22.0
            sudo rm /usr/local/bin/docker-compose
            curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
            chmod +x /usrs/local/bin/docker-compose

      - run:
          name: Setup environments
          command: |
            cp .env.sample .env
            cp web/.env.sample web/.env
            make init
            docker-compose up -d

      - run:
          name: Run tests
          command: |
            docker-compose run --rm nginx nginx -t
            docker-compose run --rm unbound unbound-checkconf
            docker-compose run -e RAILS_ENV=test --rm web bundle exec rspec

      - run:
          name: Finish job
          command: docker-compose stop

  deploy:
    docker:
       - image: circleci/ruby:2.5.1-node-browsers
    steps:
      - checkout

      - run:
          name: Bundle install
          command: |
            cd web
            bundle check || bundle install

      - run:
          name: Setup enrivonments
          command: |
            cd web
            cp .env.sample .env

      - run:
          name: Deploy to DigitalOcean's server from production branch
          command: |
            cd web
            bundle exec cap production deploy
            bundle exec cap production passenger:restart

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: production
