# https://circleci.com/docs/2.0/deployment-integrations/#capistrano
# https://github.com/CircleCI-Public/circleci-demo-docker/blob/docker-compose/.circleci/config.yml

version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout

      - run:
          name: Install docker-compose
          command: |
            curl -L https://github.com/docker/compose/releases/download/1.19.0/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose

      - run:
          name: Build images
          command: |
            docker-compose build

      - run:
          name: Setup test environment
          command: |
            docker-compose run --rm web bundle install
            docker-compose run --rm web bundle exec rails db:setup
            docker-compose run --rm -e RAILS_ENV=test web bundle exec rails db:migrate
            docker-compose run --rm web bundle exec rails db:seed

      - run:
          name: Run tests
          command: |
            docker-compose run --rm -e RAILS_ENV=test web bundle exec rspec

# TODO: configure remote server (Docker)
#   deploy:
#     docker:
#       - image: circleci/ruby:2.5.1-node-browsers
#     steps:
#       - checkout
#
#       - run:
#           name: Bundle install
#           command: |
#             cd web
#             bundle check || bundle install
#
#       - run:
#           name: Deploy to DigitalOcean's server from production branch
#           command: |
#             cd web
#             bundle exec cap production deploy
#
# workflows:
#   version: 2
#   build-deploy:
#     jobs:
#       - build
#       - deploy:
#           requires:
#             - build
#           filters:
#             branches:
#               only: production
