# この playbook は、アプリケーションの *一番最初の* 立ち上げにのみ利用することを想定しています
# CI によるデプロイをさせる前に、ローカルの環境に ansible maneger をインストールし、
# リモートにバージョン 0 を（いわゆる staging として）起動させるために使うものです
---
- hosts: all
  remote_user: ubuntu
  become: yes
  become_method: sudo

  tasks:
  - name: Clone from GitHub
    git:
      repo: https://github.com/czc-dev/Ordering-system.git
      dest: /home/ubuntu/orderingsystem

  - name: Generate .env by coping .env.sample
    command: cp .env.sample .env
    args:
      chdir: /home/ubuntu/orderingsystem

  - name: Copy master.key to remote
    copy:
      src: ~/working/czc-dev/ordering/config/master.key
      dest: /home/ubuntu/orderingsystem/config
      owner: ubuntu
      group: ubuntu
      mode: '0644'

  - name: Build production image and setup database
    command: make production
    args:
      chdir: /home/ubuntu/orderingsystem

  - name: Clean up
    command: docker system prune -f
